### ISSUE TITLE
Is there a way to insert @here or @channel in args

### ISSUE THREAD

**Issue by IvanNoronha-TomTom** [Ilshidur/action-slack#130]
Snippet from the workflow yaml I'm using
```
    steps:
      - name: Send PR details to slack for review
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_CHANNEL: channel-name
        uses: Ilshidur/action-slack@2.0.2
        with:
          args: "@here Please review the pull request {{ EVENT_PAYLOAD.pull_request.html_url }} \n \n Thanks! \n {{EVENT_PAYLOAD.pull_request.user.login}}"
```

The problem is `@here` or `@channel` does not notify the slack channel members(screenshot), 
![image](https://user-images.githubusercontent.com/73875852/114435129-70f54080-9be1-11eb-964f-e818c7d53b40.png)

@Ilshidur, I'm wondering if there's a way to ensure perhaps `@here` gets recognized by slack like this,
![image](https://user-images.githubusercontent.com/73875852/114435294-a26e0c00-9be1-11eb-8f2e-33de058c02a6.png)
